const greetingMessage =
  "Привет! Если ты попал в этот бот, то скорее всего ты хочешь развиваться в дебатах, буду рада тебе помочь \n \n ЕСЛИ ТЫ НОВИС, ОБЯЗАТЕЛЬНО ПРОЧИТАЙ ЭТО СООБЩЕНИЕ \n \n В этом боте собраны источники на каналыпаблики,лекции с материалами по дебатной теории и информативке, хорошие раунды по которым вы можете тренироваться и контакты тренеров, с которыми вы можете связаться для просьбы совета \n \n Перед тем как начать читать и смотреть все материалы, обязательно попробуй порефлексировать, какие у тебя слабые точки(вспомни фидбеки судей, спроси у ментора или тренера, который тебя судил) и качай этот момент, но!\n  \n Если ты считаешь, что плохо получается абсолютно все и тебе в целом не хватает базы знаний иди примерно по такой структуре:\n \n Каждый день хотя бы 20 минут уделяй наполнению информативной базы знаний и базы знаний по дебатной теории \n \n Старайся играть на турнирах и раундах пытаясь исправить ошибки, которые допускаешь, всегда рефликсируй над речами и внимательно слушай фид чтобы понять их \n \n Составь план с дедлайном и списком тем, которые хочешь изучить(спроси у старика какие стоит изучать, если сам не уверен) и ошибками в речах, которые хочешь исправить \n \n Тренируйся сам (пиши кейсы, записывай свои речи на диктофон и рефлексируй, переслушивай речи сильных стариков, суди раунды с видеотеки) \n \n Тренируйся с сокодругим человеком, вот статья как можно тренироваться с соко: \n \n В дебатной структуре, проработай: \n анализ резолюции(понимание какие идеи подходят под резу)\n фрейминг \n причинно-следственную связь(ризонинги и импакты) \n доказательство важности импактов \n видение игры(понимание кто выигрывает, а кто проигрывает и почему) \n ребаттл (отбивка чужих аргументов) \n сравнения(объяснение почему вы выигрываете) \n  Всегда качай идейность и информативку, тут нельзя достичь потолка \n\n нажми на команду /info, чтобы открыть эту сокровищницу ахах";
const infoMessage =
  "/getData - материалы по дебатам на русском \n/contacts - контакты тренеров, к кому можешь обратиться за советом или вопросом, отправить речь чтобы получить фидбек и др";
const articles =
  "хэндбук (сокровищница трушная) https://m.vk.com/thedebatinghandbook?from=groups \nпуть дебатера https://t.me/Debate22 \n путь дебатера 2.0 https://t.me/debate222 \n дебатляндия https://t.me/debatekek \n славяне https://t.me/slaviaanka_v_XO (https://telegra.ph/TO-SUM-IT-UP-12-07 - навигация статей в славянах)\n инфо пузыри и не только https://t.me/debatyblya \n паблик ростовской лиги https://m.vk.com/raccoon_of_debate \n кейсотека https://m.vk.com/caseaday?from=groups \n статьи https://vk.com/trening_ne_dlya_lohov \n заметки по базовым темам - https://t.me/papercuptrain \n закреп - https://t.me/oskonbaydebates/21 \nпереводы лекций топовых уников мира - https://vk.com/topuniversity_lectures";
const lectures =
  "в закрепе есть полный курс по дебатам https://t.me/dushka_polnaya \n тренинги на базовые темы - https://www.youtube.com/@DCSynergyAlmaU \n тоже тренинги по аргументации - https://www.youtube.com/@rus-languagedebateinestoni9077 \n тренинги по дебатной теории и информативке https://www.youtube.com/@debateonline9551 \n дебайты - старые тренинги - https://m.vk.com/debateonline?from=groups \n парламентские дебаты - старые тренинги - https://m.vk.com/parldebates?from=groups \n серия тренингов - https://vk.com/debate_hse \n https://www.youtube.com/channel/UCT6HEzQDttONWi5kdW5Je-A— канал с разборами тем, треннингами и записями турниров \n https://www.youtube.com/channel/UC1Cdkqn2WrTxLaLfmo_Y.. (English) — треннинги Европейского дебатного сообщества \n https://www.youtube.com/channel/UCbx6dh3PTCY3q4TqIaXHfpQ/videos (English) — канал с большим выбором треннингов от друзей из Астаны \n рдл - https://www.youtube.com/@RostovDebateLeague/videos \nзаписи тренингов одной академии дебатов - https://drive.google.com/drive/u/0/folders/1Qs9t_ISYhgchxhruJwzJ6Xng2ll_UFz6";
const development =
  "https://telegra.ph/Kak-za-odin-god-projti-put-ot-novichka-k-topu-03-26 - методы тренировок  \n https://telegra.ph/pokoj-nam-tolko-snitsya-06-02 - о составлении плана и методах тренировок \n https://telegra.ph/kak-debatit-debatu-12-07 - необходимые скиллы в дебатах, как их натренить  про тактики в дебатах";
const finals =
  "старые раунды - https://www.youtube.com/@user-ns7yh6pp6n \nрусская видеотека - https://disk.yandex.ru/d/CLJVbfQ1D_bpgQ \nбишкекская видеотека - https://vk.com/vidbishdc \n финалы - https://www.youtube.com/@DebateClubParassat \n Финал CA 2018 https://youtu.be/z7g9KIKTiSQ \n Финал Manas Cup 2018 https://youtu.be/ioKZ8oNkTYM \n Финал Кубок Свободы 2019 https://youtu.be/Z9qGxR0s7-8";
const knowledgeData =
  "https://www.youtube.com/@Nogoibay канал легенды бдц \n есть плейлист с тренингами по дебатам про разную информативку - https://www.youtube.com/@astanadebateunion9733 \n информативка - https://vk.com/page-11610529_52089810 \n славяне https://t.me/slaviaanka_v_XO \n хэндбук (сокровищница трушная) https://m.vk.com/thedebatinghandbook?from=groups \n книга “Гарри Поттер и методы рационального мышления” - для понимания когнитивных искажений \n https://www.youtube.com/@toplesofficial - социалка \n https://www.youtube.com/watch?v=7NbXw_ofP3M - международные отношения \n https://www.youtube.com/watch?v=N7kuQKwzz2I - социалка(можно брать готовые аргументы)";
const articlesTDH =
  "Подборка статей по аргументации из хэндбука: \n Аргументация: \n Углубленная аргументация - https://vk.com/@thedebatinghandbook-uglublennaya-argumentaciya \n Семь ошибок в аргументации, которых нужно избежать - https://vk.com/@thedebatinghandbook-sem-oshibok-v-argumentacii-kotoryh-nuzhno-izbezhat \n Отбивка - https://vk.com/@thedebatinghandbook-otbivka \n Контестуализация/характеризация - https://vk.com/@thedebatinghandbook-kontestualizaciyaharakterizaciya \n Аналитические речи - https://vk.com/@thedebatinghandbook-analiticheskie-rechi \n Принципиальные аргументы - https://vk.com/@thedebatinghandbook-principialnye-argumenty \n Сравнительная аргументация - https://vk.com/@thedebatinghandbook-sravnitelnaya-argumentaciya \n Речи заместителей - https://vk.com/@thedebatinghandbook-rechi-zamestitelei";
const contacts =
  "можешь писать: \n 1) Айя - https://t.me/Aiaiiiaia \n 2) Арина - https://t.me/avevara \n 3) Коля - https://t.me/Nicolay_Konyashin \n 4) Айдина - https://t.me/sohighhhhh \n 5) Артемий - https://t.me/Artemii_konova \n 6) Карина - https://t.me/Soticksz \n 7) Макс - https://t.me/xarvi22 \n 8) Туран - https://t.me/Ismtu_Attok \n 9) Мурат - https://t.me/Hakimmurat \n 10) Алексей - https://t.me/alxvlrvch \n 11) Камила - https://t.me/applecinnamonpie \n 12) Эрен - https://t.me/kizmaballz \n 13) Касиет - https://t.me/mbihateyou \n 14) Нурислам - https://t.me/TochilkaKarandash \n 15) Алима - https://t.me/marzipanmadchen \n 16) Алина - https://t.me/kemeex \n 17) Абай - https://t.me/tygydyktygydykk \n 18) Рената - https://t.me/renataramil \n 19) Алим - https://t.me/Kailkastis \n 20) Рамина - https://t.me/hiddendevil28 \n \n Также не стесняйся спрашивать совета и вопросы по дебатам у стариков БДЦ и других сообществ(ps: никто не кусается, не стоит боятся)";
module.exports = {
  greetingMessage,
  infoMessage,
  articles,
  lectures,
  development,
  finals,
  knowledgeData,
  articlesTDH,
  contacts,
};
